name: Self-Approve PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == github.repository_owner
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Auto-approve PR
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
